### PR TITLE
[postgres] Update CDS Services to 2.5.0

### PR DESCRIPTION
**Pull request by mofterdinger**

### CODE REVIEW

**Comment by StefanHenke** [comment]
I believe PR #279 was faster :)

**Comment by vmikhailenko** [comment]
"@cap-js/postgres": "~1" in `package.json`? Looks like I forgot to update it after the bug there was fixed.

**Comment by mofterdinger** [comment]
> "@cap-js/postgres": "~1" in `package.json`? Looks like I forgot to update it after the bug there was fixed.
> 
> Done here [a84e8c5](https://github.com/SAP-samples/cloud-cap-samples-java/commit/a84e8c5d345c06faba3203fbb7d6d7e121ced8d1)

What do you suggest ?

**Comment by vmikhailenko** [comment]
> > "@cap-js/postgres": "~1" in `package.json`? Looks like I forgot to update it after the bug there was fixed.
> > Done here [a84e8c5](https://github.com/SAP-samples/cloud-cap-samples-java/commit/a84e8c5d345c06faba3203fbb7d6d7e121ced8d1)
> 
> What do you suggest ?

To update it. I have pushed the commit to do so.

**Review by vmikhailenko — APPROVED** [review]

**Pull request merged**
