### PR TITLE
Use H2 as in-memory database

### PR DESCRIPTION
**Pull request by beckermarc**
To be improved in the future in `cds-services`:
- Auto-detection of H2 as embedded database
- Ability to disable detection of datasources from environment (e.g. `default-env.json`) -> previously covered by explicit `spring.datasource.url` configuration

### CODE REVIEW

**Review by agoerler — APPROVED** [review]

**Comment by beckermarc** [comment]
@mofterdinger can you please also have a look at this PR. @agoerler apparently is not a contributer yet 😢 😄

**Review by mofterdinger — APPROVED** [review]
As we promote using the H2 database now in the public sample application, we should also consider to change the cds-services-archetype to create initial projects with H2 support.

**Comment by beckermarc** [comment]
Sure, my idea was to pioneer it in the samples first to find any undiscovered issues. If we feel comfortable with H2 we can also adapt our default project generation :)

**Comment by mofterdinger** [comment]
This change has a side effect. If there is a default-env.json laying around from previous tests against a HANA DB, the cap-runtime initialises the datasource with these settings, even I don't choose profile `cloud`. This was not the case in the previous project configuration.

**Comment by beckermarc** [comment]
Yes, this is a known side-effect (see description above). To be discussed if this is desirable or not, see also our internal PR in cds-services on "Improvements for H2". There I added an explicit flag to disable this datasource auto-configuration from default-env.json.

**Comment by beckermarc** [comment]
BTW: These are exactly the reasons for pioneering it in the samples first and not immediately pushing it out with our archetype :)

**Comment by mofterdinger** [comment]
Pioneering is good, but I prefer to do it internally and prepare everything. My comment wasn't about updating the archetype before we gain some experience with replacing Sqlite with H2.

**Pull request merged**
