### PR TITLE
cleanup .cdsrc.json

### PR DESCRIPTION
**Pull request by mofterdinger**
See: https://github.com/SAP-samples/cloud-cap-samples-java/pull/262

### CODE REVIEW

**Comment by beckermarc** [comment]
According to my understanding the file could even be a completely empty JSON object or even removed, as also profile java is auto-configured.

**Comment by mofterdinger** [comment]
> According to my understanding the file could even be a completely empty JSON object or even removed, as also profile java is auto-configured.

ok, I will try without .cdsrc.json.

**Comment by mofterdinger** [comment]
cool, it works withoud a `.cdsrc.json`, the cds build works fine and bookshop starts.

**Comment by beckermarc** [comment]
Don't we use `.cdsrc.json` also as an indicator in our Maven Plugin for the root of the project?
Maybe better keep an empty file? If we remove it, we should I think avoid putting config into package.json but rather readd `.cdsrc.json` if we need it.

**Comment by mofterdinger** [comment]
The `cds-maven-plugin` uses beside the `.cdsrc.json` also the `package.json` to find the build root. So, this is not problem, the maven build works fine without a `.cdsrc.json`:
```bash
[INFO] CdsMojo: Using /Users/d032842/SAPDevelop/.m2/repository/com/sap/cds/cds-maven-plugin/cache/unpacked/18.18.2/unpacked-18.18.2-darwin-x64.tar.gz/node-v18.18.2-darwin-x64/bin/npx provided by goal install-node.
[INFO] CdsMojo: Using directory containing a package.json as working directory: /Users/d032842/SAPDevelop/git/cloud-cap-samples-java
[INFO] CdsMojo: Executing [/Users/d032842/SAPDevelop/.m2/repository/com/sap/cds/cds-maven-plugin/cache/unpacked/18.18.2/unpacked-18.18.2-darwin-x64.tar.gz/node-v18.18.2-darwin-x64/bin/npx, -c, cds version] in working directory /Users/d032842/SAPDevelop/git/cloud-cap-samples-java
[INFO] CdsMojo: Using configured working directory: /Users/d032842/SAPDevelop/git/cloud-cap-samples-java
[INFO] CdsMojo: Executing [/Users/d032842/SAPDevelop/.m2/repository/com/sap/cds/cds-maven-plugin/cache/unpacked/18.18.2/unpacked-18.18.2-darwin-x64.tar.gz/node-v18.18.2-darwin-x64/bin/npx, -c, cds build --for java] in working directory /Users/d032842/SAPDevelop/git/cloud-cap-samples-java
[INFO] CdsMojo: [cds] - building project [/Users/d032842/SAPDevelop/git/cloud-cap-samples-java], clean [true]
[cds] - cds-dk [7.3.0], cds [7.3.0], compiler [4.3.0], home [/Users/d032842/SAPDevelop/git/cloud-cap-samples-java/node_modules/@sap/cds]
```
[INFO] CdsMojo: Using directory containing a **package.json** as working directory: /Users/d032842/SAPDevelop/git/cloud-cap-samples-java

But yes, we can keep an empty `.cdsrc.json`, to avoid future CDS configurations in package.json.

**Review by beckermarc — APPROVED** [review]

**Pull request merged**
