### PR TITLE
Use CAP Java 3.0 ...

### PR DESCRIPTION
**Pull request by mofterdinger**
and:
- @sap/cds-dk@8.0.2
- spring-boot 3.3.1

### CODE REVIEW

**Comment by vmikhailenko** [comment]
Sidecar needs to be updated as well.

**Comment by vmikhailenko** [comment]
`package.json` on top still references `@sap/cds-dk` as 7.

**Comment by mofterdinger** [comment]
> `package.json` on top still references `@sap/cds-dk` as 7.
> 
> Revert #338?

Fixed in package.json, thanks for this hint.

**Review by beckermarc — CHANGES_REQUESTED** [review]
Please also cleanup the cds build command in srv/pom.xml and remove the opts that are no longer required

**Review by beckermarc — APPROVED** [review]

**Pull request merged**
