### PR TITLE
Fixed various CDS warnings

### PR DESCRIPTION
**Pull request by beckermarc**

### CODE REVIEW

**Comment by mofterdinger** [comment]
Hi Marc, I built this branch and I still get these cds warnings:
```
[cds] - [WARNING] db/orders.cds:20:8: Expected value help list entity “AdminService.Books” to have only one key element for “@Common.ValueList.entity” (in entity:“AdminService.OrderItems”/element:“book_ID”/“@Common.ValueList.entity”)
[cds] - [WARNING] db/orders.cds:20:8: Expected value help list entity “AdminService.Books” to have only one key element for “@Common.ValueList.entity” (in entity:“AdminService.OrderItems”/element:“book”/“@Common.ValueList.entity”)
[cds] - [WARNING] srv/admin-service.cds:10:10: “@PersonalData.DataSubjectRole” is experimental and can be changed or removed at any time, do not use productively! (in entity:“AdminService.Authors”/“@PersonalData.DataSubjectRole”)
[cds] - [WARNING] srv/cat-service.cds:14:12: “@PersonalData.DataSubjectRole” is experimental and can be changed or removed at any time, do not use productively! (in entity:“CatalogService.Authors”/“@PersonalData.DataSubjectRole”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:595:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BPContactToAddress”/element:“to_EmailAddress”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:597:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BPContactToAddress”/element:“to_FaxNumber”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:599:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BPContactToAddress”/element:“to_MobilePhoneNumber”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:601:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BPContactToAddress”/element:“to_PhoneNumber”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:603:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BPContactToAddress”/element:“to_URLAddress”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1209:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BuPaIdentification”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1211:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BuPaIndustry”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1213:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BusinessPartnerAddress”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1215:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BusinessPartnerBank”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1217:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BusinessPartnerContact”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1219:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BusinessPartnerRole”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1221:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartner”/element:“to_BusinessPartnerTax”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1547:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerAddress”/element:“to_AddressUsage”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1549:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerAddress”/element:“to_EmailAddress”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1551:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerAddress”/element:“to_FaxNumber”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1553:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerAddress”/element:“to_MobilePhoneNumber”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1555:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerAddress”/element:“to_PhoneNumber”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1557:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerAddress”/element:“to_URLAddress”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:1732:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_BusinessPartnerContact”/element:“to_ContactAddress”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:2093:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_Customer”/element:“to_CustomerCompany”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:2095:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_Customer”/element:“to_CustomerSalesArea”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:2328:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_CustomerCompany”/element:“to_CustomerDunning”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:2330:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_CustomerCompany”/element:“to_WithHoldingTax”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:2758:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_CustomerSalesArea”/element:“to_PartnerFunction”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:2760:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_CustomerSalesArea”/element:“to_SalesAreaTax”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:3283:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_Supplier”/element:“to_SupplierCompany”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:3285:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_Supplier”/element:“to_SupplierPurchasingOrg”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:3550:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_SupplierCompany”/element:“to_SupplierDunning”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:3552:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_SupplierCompany”/element:“to_SupplierWithHoldingTax”)
[cds] - [WARNING] srv/external/API_BUSINESS_PARTNER.cds:3878:3: Expected association with target cardinality ‘to many’ to have an ON-condition (in entity:“API_BUSINESS_PARTNER.A_SupplierPurchasingOrg”/element:“to_PartnerFunction”)
[cds] - [WARNING] srv/review-service.cds:14:12: “@PersonalData.DataSubjectRole” is experimental and can be changed or removed at any time, do not use productively! (in entity:“ReviewService.Authors”/“@PersonalData.DataSubjectRole”)
[cds] - [WARNING] Expected target “AdminService.Books” to have only one key element
```
Should they also be fixed ?

Thanks,
Markus

**Review by mofterdinger — APPROVED** [review]

**Comment by beckermarc** [comment]
> Should they also be fixed ?

I guess so, but they are actually false positives or too loud warnings. It is not so easy to fix them in our project, but they should be rather fixed in the CDS tooling I think.

**Comment by bugwelle** [comment]
@beckermarc We will reduce the spam of the `Expected association with target cardinality` message and remove it for external services for which the user has no way to change it (by looking if there are no foreign keys). I saw this issue by luck, but in general you can ping us if you think that messages are useless (e.g. due to it being an external service). :)

**Comment by beckermarc** [comment]
Thanks @bugwelle. Although the user actually has influence on that. When using `cds import --as cds`, the imported CDS even contains hints to restore ON conditions, if required. See for example here: https://github.com/SAP-samples/cloud-cap-samples-java/blob/main/srv/external/API_BUSINESS_PARTNER.cds#L594-L595
However I still think it is not really helpful to throw all these warnings at the user during build.

What I am also not quite getting is the warning about `@PersonalData.SubjectRole`. This annotation is meanwhile even documented in CAPire, so why is it warned as "experimental"? CAPire: https://cap.cloud.sap/docs/guides/data-privacy/audit-log#data-subject

**Comment by bugwelle** [comment]
@beckermarc The corresponding OData vocabulary has only been marked non-experimental 13 days ago. The next cds-compiler versions won't emit the message. :-)

Regarding the ON-condition: True, but I doubt that each user will go through an imported service to change an ON-condition. According to my colleagues, the empty foreign key list is what was decided on to use for to-many associations. I think the proposed alternative was something like `on 1=1`. If users explicitly write an empty foreign key list (in this case the importer), I'd interpret it was "I know what I'm doing".

**Comment by beckermarc** [comment]
Ah, this warning came from the OData vocabulary. Interesting!
Yes we decided on the empty foreign key list and the `@cds.ambiguous` annotation. If you want to make an even more "defensive" change you could also think about omitting the warning only in case the `@cds.ambiguous` annotation is present,  but I am also fine with the current proposal to "accept" an empty keys definition.

**Comment by bugwelle** [comment]
> Ah, this warning came from the OData vocabulary. Interesting!

Yes, the compiler imports the OData definitions from time to time. For cds-compiler v4.0.0, the vocabulary was marked "experimental". For v4.1.0, it no longer is. See https://github.com/SAP/odata-vocabularies/blob/main/vocabularies/PersonalData.md
This commit removed the "experimental" marker: https://github.com/SAP/odata-vocabularies/commit/dd01c4c7ea7b9131276c05c1567206ba85a9e25c

> …`@cds.ambiguous`…

Thanks! I was not aware of this annotation.

**Pull request merged**
