### PR TITLE
minor: align with https://cap.cloud.sap/docs/java/multitenancy#bindin…

### PR DESCRIPTION
**Pull request by andre68723**
…g-it-together

change srv-url/url -> srv/url to make it consistent to documentation

### CODE REVIEW

**Comment by beckermarc** [comment]
@andre68723 thanks for the contribution and pointing us to that difference!
Looking at that code again I'd personally like it best if it were as simple as `srv/url` in the end. 

@MarcelMerkle any reason why we used `srv` twice in the combined property name? Should we also simplify the documentation or do we want to keep it as is and merge this PR to align the sample with the docs?

**Comment by beckermarc** [comment]
@andre68723 Also mentioned that for consistency we should also adapt `app-url` to simply `app/app-url` or `app/url` depending which way we choose to go.

**Comment by MarcelMerkle** [comment]
@beckermarc No, there is no specific reason. I think it was just like that in the example that I used. We can also use `srv/url` from my perspective.

@andre68723 I think, we should change it in the mta-single-tenant.yaml as well then.

**Review by beckermarc — APPROVED** [review]

**Review by MarcelMerkle — APPROVED** [review]

**Comment by beckermarc** [comment]
As we know that andre68723 and Andre Voigtmann are the same person I am merging this PR :)

**Pull request merged**
