### PR TITLE
PostgreSQL: Demonstrate integration-tests module with Testcontainers

### PR DESCRIPTION
**Pull request by mofterdinger**
This PR demonstrates how we can leverage Testcontainers in a integration-tests module and using the failsafe-plugin to execute the tests. This PR is just proposal how it could look like.

### CODE REVIEW

**Comment by vmikhailenko** [comment]
I am fine with this in a didactic sense. But the existing test already uses the Postgres in a test container...

**Comment by mofterdinger** [comment]
> I am fine with this in a didactic sense. But the existing test already uses the Postgres in a test container...

Yes, I know we show already the Testcontainers setup. The configuration in a separate integration-tests module is different, maybe we just keep it in an additional branch.

**Comment by beckermarc** [comment]
>  maybe we just keep it in an additional branch.

Please don't introduce even more branches, that need to be kept up-to-date :)

**Comment by mofterdinger** [comment]
ok, pushed it into our internal repo. I'm using this kind of setup in another project and I just wanted to share.

**Comment by beckermarc** [comment]
I wasn't arguing against merging this branch! I just wanted to make sure that we do not add more branches, but why not merge this, if it is useful?

**Comment by mofterdinger** [comment]
> I wasn't arguing against merging this branch! I just wanted to make sure that we do not add more branches, but why not merge this, if it is useful?

yes, I know, not sure if this setup is relevant for stakeholders, I just wanted to show it with the bookshop pg.

**Pull request closed without merging**
